export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_ACTIVE_FILTER_TYPE = 'SET_ACTIVE_FILTER_TYPE';

export const SET_SPECIES_FILTER_TYPE = 'SET_SPECIES_FILTER_TYPE';
export const SET_STATUS_FILTER_TYPE = 'SET_STATUS_FILTER_TYPE';
export const SET_GENDER_FILTER_TYPE = 'SET_GENDER_FILTER_TYPE';